from krrood.patterns.code_generation.specs.specs import (
    BaseClassSpec,
    ClassMethodSpec,
    ClassTransformationSpec,
    DelegationSpec,
    FactoryMethodSpec,
    FieldSpec,
    ImportSpec,
    MemberSpec,
    MethodSpec,
    ModuleTransformationSpec,
    ParameterSpec,
    PropertySpec,
    RoleClassTransformationSpec,
    StaticMethodSpec,
)
